### ISSUE TITLE
Support for redmine 4.x

### ISSUE THREAD

**Issue by matevz** [farend/scm-creator#18]
Plugins crashes with the following error when using it on redmine 4.0.4:
```
$ rake redmine:plugins
...
/opt/redmine/redmine-4.0.4/plugins/redmine_scm/lib/scm_repositories_helper_patch.rb:10:in `block in included'
/opt/redmine/redmine-4.0.4/plugins/redmine_scm/lib/scm_repositories_helper_patch.rb:7:in `class_eval'
/opt/redmine/redmine-4.0.4/plugins/redmine_scm/lib/scm_repositories_helper_patch.rb:7:in `included'
/opt/redmine/redmine-4.0.4/plugins/redmine_scm/init.rb:27:in `include'
/opt/redmine/redmine-4.0.4/plugins/redmine_scm/init.rb:27:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `instance_exec'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:605:in `catch'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:199:in `block in halting'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `each'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `invoke_before'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:131:in `run_callbacks'
/var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/reloader.rb:89:in `prepare!'
/var/lib/gems/2.5.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
/var/lib/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/opt/redmine/redmine-4.0.4/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/lib/gems/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/var/lib/gems/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/opt/redmine/redmine-4.0.4/lib/tasks/redmine.rake:57:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
```

**Comment by ishikawa999** [comment]
Thank you for sharing this issue.
It is a problem related to #15.

**Comment by ishikawa999** [comment]
@matevz 

I changed it to be able to use plug-in with redmine 4.0.4. (https://github.com/farend/scm-creator/issues/15#issuecomment-513600704)
Could you get the latest plug-in and see that it works?

**Comment by matevz** [comment]
I can confirm that the plugin works with redmine 4.0.4. Thanks!
