### ISSUE TITLE
Support for redmine 4.1.1

### ISSUE THREAD

**Issue by dkhachyan** [farend/scm-creator#19]
Hi!
Plugin successfully creates repo but returns http 500

```
F, [2021-08-19T21:43:20.872953 #1] FATAL -- : NoMethodError (undefined method `created_with_scm' for #<Repository::Git:0x00007f924494c9a0>
Did you mean?  created_on_was):
F, [2021-08-19T21:43:20.872995 #1] FATAL -- :
F, [2021-08-19T21:43:20.873028 #1] FATAL -- : plugins/redmine_scm/lib/scm_repositories_controller_patch.rb:52:in `create'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
I, [2021-08-19T21:43:29.699573 #1]  INFO -- : Started POST "/projects/tst/repositories" for 172.19.0.1 at 2021-08-19 21:43:29 +0000
I, [2021-08-19T21:43:29.700829 #1]  INFO -- : Processing by RepositoriesController#create as HTML
I, [2021-08-19T21:43:29.700934 #1]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"ZThpeEgJw+sib/ADPTKZRjAe4i1ZNhhQ53JqKP8gOvO/HBGnNYFjYX5QwXuRWn04AwjgClz02/8qwSTUyAMJ8w==", "repository_scm"=>"Git", "repository"=>{"is_default"=>"1", "identifier"=>"tst", "url"=>"/usr/src/redmine/files/git/tst.git", "path_encoding"=>"UTF-8", "report_last_commit"=>"1"}, "commit"=>"Создать новое хранилище", "operation"=>"add", "project_id"=>"tst"}
I, [2021-08-19T21:43:29.713494 #1]  INFO -- :   Current user: admin (id=1)
I, [2021-08-19T21:43:29.726265 #1]  INFO -- : Creating reporitory: /usr/src/redmine/files/git/tst.git
Initialized empty Git repository in /usr/src/redmine/files/git/tst.git/
172.19.0.1 - - [19/Aug/2021:21:43:29 UTC] "POST /projects/tst/repositories HTTP/1.0" 500 648
```

**Comment by ishikawa999** [comment]
Sorry, I am not currently using this plugin and cannot maintain it.
I apologize for not being able to help you.
I will archive this repository.
